CREATE DATABASE ReservaPistasDeportivas
go
USE ReservaPistasDeportivas
GO


CREATE TABLE PISTA
( 
	ID_PISTA             int  NOT NULL ,
	NUM_PISTA            int  NOT NULL ,
	ID_TIPO_PISTA        int  NOT NULL 
)
go



ALTER TABLE PISTA
	ADD CONSTRAINT XPKCancha PRIMARY KEY  CLUSTERED (ID_PISTA ASC)
go



CREATE TABLE RESERVA
( 
	ID_RESERVA           char(18)  NOT NULL ,
	ID_USUARIO           int  NOT NULL ,
	ID_PISTA             int  NOT NULL ,
	ID_TARIFA            int  NOT NULL ,
	FECHA                date  NOT NULL 
)
go



ALTER TABLE RESERVA
	ADD CONSTRAINT XPKReserva PRIMARY KEY  CLUSTERED (ID_RESERVA ASC,ID_PISTA ASC,ID_USUARIO ASC,ID_TARIFA ASC)
go



CREATE TABLE TARIFA
( 
	ID_TARIFA            int  NOT NULL ,
	ID_TIPO_PISTA        int  NOT NULL ,
	HORA_INICIO          varchar(5)  NOT NULL ,
	HORA_FIN             varchar(5)  NOT NULL ,
	PRECIO               decimal(18,2)  NOT NULL 
)
go



ALTER TABLE TARIFA
	ADD CONSTRAINT XPKTarifa PRIMARY KEY  CLUSTERED (ID_TARIFA ASC)
go



CREATE TABLE TIPO_PISTA
( 
	ID_TIPO_PISTA        int  NOT NULL ,
	NOMBRE_TIPO          varchar(50)  NOT NULL 
)
go



ALTER TABLE TIPO_PISTA
	ADD CONSTRAINT XPKTipo_Cancha PRIMARY KEY  CLUSTERED (ID_TIPO_PISTA ASC)
go



CREATE TABLE USUARIO
( 
	ID_USUARIO           int  NOT NULL ,
	NOMBRE_USUARIO       varchar(30)  NOT NULL ,
	NOMBRE               varchar(50)  NOT NULL ,
	APELLIDOS            varchar(80)  NOT NULL ,
	MOVIL                varchar(12)  NOT NULL ,
	EMAIL                varchar(30)  NOT NULL ,
	SEXO                 varchar(1)  NOT NULL ,
	FECHA_NACIMIENTO     date  NOT NULL ,
	FECHA_ALTA           date  NOT NULL ,
	PASSWORD             varchar(30)  NOT NULL ,
	ES_ADMINISTRADOR     varchar(2)  NOT NULL 
)
go



ALTER TABLE USUARIO
	ADD CONSTRAINT XPKUsuario PRIMARY KEY  CLUSTERED (ID_USUARIO ASC)
go




ALTER TABLE PISTA
	ADD CONSTRAINT R_4 FOREIGN KEY (ID_TIPO_PISTA) REFERENCES TIPO_PISTA(ID_TIPO_PISTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE RESERVA
	ADD CONSTRAINT R_7 FOREIGN KEY (ID_PISTA) REFERENCES PISTA(ID_PISTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE RESERVA
	ADD CONSTRAINT R_8 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE RESERVA
	ADD CONSTRAINT R_9 FOREIGN KEY (ID_TARIFA) REFERENCES TARIFA(ID_TARIFA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE TARIFA
	ADD CONSTRAINT R_5 FOREIGN KEY (ID_TIPO_PISTA) REFERENCES TIPO_PISTA(ID_TIPO_PISTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


